function p_pos = get_pos_from_2D_projections(bc_2d, bc_3d, p_t)
p_t = reshape(p_t,1,[]);
% find 3D positions of the intersecting points
c2d_ori = cell2mat( ...
    arrayfun(fit_bezier_curve(bc_2d), ...
    p_t, 'UniformOutput', false)' ...
    );
c3d_ori = cell2mat( ...
    arrayfun(fit_bezier_curve(bc_3d), ...
    p_t, 'UniformOutput', false)' ...
    );
p_pos = [c2d_ori, c3d_ori(:,2)];

end